DEFRA/epr-calculator-api

src/EPR.Calculator.API.Data/Migrations-Readme.txt, src/EPR.Calculator.API.Data/Scripts/migrations.sql
Fix the migrations SQL so that they can be run multiple times with checks
=> Update Migrations Sql Script - UD

src/EPR.Calculator.API/Controllers/LapcapDataController.cs
Lapcap GET route change - `/v1/lapcapdata/{param_year}`
=> Lapcap GET route change

src/EPR.Calculator.API.UnitTests/LAPCAPParameterSettingMapperTests.cs, src/EPR.Calculator.API.UnitTests/LapcapDataControllerTests.cs, src/EPR.Calculator.API/Dtos/LapCapParameterDto.cs, src/EPR.Calculator.API/Mappers/LapcapDataParameterSettingMapper.cs
A small Bug has been created by tester notices the time stamp when user has updated was not coming right
=> added effective from field that is needed for front end

src/EPR.Calculator.API.Data/ApplicationDBContext.cs, src/EPR.Calculator.API.Data/DataModels/CalculatorRun.cs, src/EPR.Calculator.API.Data/DataModels/CalculatorRunOrganisationDataDetail.cs, src/EPR.Calculator.API.Data/DataModels/CalculatorRunOrganisationDataMaster.cs, src/EPR.Calculator.API.Data/DataModels/CalculatorRunPomDataDetail.cs, src/EPR.Calculator.API.Data/DataModels/CalculatorRunPomDataMaster.cs, src/EPR.Calculator.API.Data/DataModels/DefaultParameterSettingMaster.cs, src/EPR.Calculator.API.Data/DataModels/LapcapDataMaster.cs, src/EPR.Calculator.API.Data/DataModels/OrganisationData.cs, src/EPR.Calculator.API.Data/DataModels/PomData.cs, src/EPR.Calculator.API.Data/Migrations/20241004134649_CalcRunTables.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241004134649_CalcRunTables.cs, src/EPR.Calculator.API.Data/Migrations/20241007082551_CalcRunMinorChanges.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241007082551_CalcRunMinorChanges.cs, src/EPR.Calculator.API.Data/Scripts/migrations.sql
Feature/428543 - Adding new tables
1. calculator_run_organization_data_detail
2. calculator_run_organization_data_master
3. calculator_run_pom_data_detail
4. calculator_run_pom_data_master
5. organization_data [Staging table]
6. pom_data [Staging table]
And adding the relationships from calculator_run table to
1. calculator_run_organization_data_master
2. calculator_run_pom_data_master
3. lapcap_data_master
4. default_parameter_setting_master
=> Calculator Run related Table changes - 428543

pipelines/deployment-pipeline.yaml, src/EPR.Calculator.API.UnitTests/EPR.Calculator.API.UnitTests.csproj, src/EPR.Calculator.API.UnitTests/GlobalExceptionHandlerTests.cs, src/EPR.Calculator.API/Exceptions/GlobalExceptionHandler.cs, src/EPR.Calculator.API/Program.cs
=> Added Global Exception Handler for Web API

src/EPR.Calculator.API.UnitTests/BaseControllerTest.cs, src/EPR.Calculator.API.UnitTests/CalculatorControllerTests.cs, src/EPR.Calculator.API.UnitTests/EPR.Calculator.API.UnitTests.csproj, src/EPR.Calculator.API.UnitTests/GlobalSuppressions.cs, src/EPR.Calculator.API.UnitTests/Helpers/ConfigurationItems.cs, src/EPR.Calculator.API.UnitTests/LapcapDataControllerTests.cs, src/EPR.Calculator.API.UnitTests/appsettings.Test.json, src/EPR.Calculator.API/Controllers/CalculatorController.cs, src/EPR.Calculator.API/Dtos/CreateCalculatorRunDto.cs, src/EPR.Calculator.API/EPR.Calculator.API.csproj, src/EPR.Calculator.API/Models/CalculatorRunMessage.cs, src/EPR.Calculator.API/Program.cs, src/EPR.Calculator.API/appsettings.Development.json
Create a new endpoint - Http Post for Starting a new Run
1. Validate Calc Run Name
2. Validate if a new Run is Possible
3. Create a new Entry into Calc table
4. return a 202 response
=> Initiate Calculator Run

src/EPR.Calculator.API.Data/ApplicationDBContext.cs, src/EPR.Calculator.API.Data/DataModels/OrganisationData.cs, src/EPR.Calculator.API.Data/DataModels/PomData.cs, src/EPR.Calculator.API.Data/Migrations/20241018110438_OrganisationAndPomChanges.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241018110438_OrganisationAndPomChanges.cs, src/EPR.Calculator.API.Data/Scripts/migrations.sql
Table  Design changes
- Rename - Organisation_data from Organization_data where we need s instead of z
- Remove Primary Keys for the tables Organisation_data and pom_data tables.
=> Organisation and Pom Data Migration

src/EPR.Calculator.API.Data/DataModels/CalculatorRunOrganisationDataDetail.cs, src/EPR.Calculator.API.Data/DataModels/CalculatorRunPomDataDetail.cs, src/EPR.Calculator.API.Data/DataModels/OrganisationData.cs, src/EPR.Calculator.API.Data/DataModels/PomData.cs, src/EPR.Calculator.API.Data/Migrations/20241021110702_CalcRunPomAndOrganisationRemoveKeys.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241021110702_CalcRunPomAndOrganisationRemoveKeys.cs, src/EPR.Calculator.API.Data/Migrations/20241021130056_OrganisationIdAndSubsidaryIdNullable.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241021130056_OrganisationIdAndSubsidaryIdNullable.cs, src/EPR.Calculator.API.Data/Migrations/20241024125526_OrganisationIDToInt.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241024125526_OrganisationIDToInt.cs, src/EPR.Calculator.API.Data/Migrations/20241024134320_PackagingMaterialWeightToDouble.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241024134320_PackagingMaterialWeightToDouble.cs, src/EPR.Calculator.API.Data/Scripts/migrations.sql, src/EPR.Calculator.API.UnitTests/BaseControllerTest.cs, src/EPR.Calculator.API.UnitTests/CalculatorInternalControllerTest.cs, src/EPR.Calculator.API/Controllers/CalculatorController.cs, src/EPR.Calculator.API/Controllers/CalculatorInternalController.cs, src/EPR.Calculator.API/Dtos/UpdateRpdStatus.cs, src/EPR.Calculator.API/Models/RpdStatusValidation.cs, src/EPR.Calculator.API/Program.cs, src/EPR.Calculator.API/Validators/IRpdStatusDataValidator.cs, src/EPR.Calculator.API/Validators/RpdStatusDataValidator.cs, src/EPR.Calculator.API/Wrapper/IOrgAndPomWrapper.cs, src/EPR.Calculator.API/Wrapper/OrgAndPomWrapper.cs
- Create a new Http POST endpoint which is intended to be used internally
- The Endpoint will be used by Azure Functions to update the RPD Status to confirm a successful or unsuccessful run
- The Http endpoint returns 201, 400, 424 or 500 response
=> Load & status update to RPD data - Create new POST endpoint (Internal)

src/EPR.Calculator.API.Data/ApplicationDBContext.cs, src/EPR.Calculator.API.Data/DataModels/CalculatorRun.cs, src/EPR.Calculator.API.Data/DataModels/CalculatorRunOrganisationDataDetail.cs, src/EPR.Calculator.API.Data/DataModels/CalculatorRunPomDataDetail.cs, src/EPR.Calculator.API.Data/DataModels/CostType.cs, src/EPR.Calculator.API.Data/DataModels/Country.cs, src/EPR.Calculator.API.Data/DataModels/CountryApportionment.cs, src/EPR.Calculator.API.Data/DataModels/Material.cs, src/EPR.Calculator.API.Data/DataModels/OrganisationData.cs, src/EPR.Calculator.API.Data/DataModels/PomData.cs, src/EPR.Calculator.API.Data/DataModels/ProducerDetail.cs, src/EPR.Calculator.API.Data/DataModels/ProducerReportedMaterial.cs, src/EPR.Calculator.API.Data/Migrations/20241025140420_CalculationResultsTables.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241025140420_CalculationResultsTables.cs, src/EPR.Calculator.API.Data/Migrations/20241028092305_CreateMasterDataForCalcResultsTables.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241028092305_CreateMasterDataForCalcResultsTables.cs, src/EPR.Calculator.API.Data/Migrations/20241028114313_AddNewColumnSubmissionPeriodDescToPomAndOrganisationTables.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20241028114313_AddNewColumnSubmissionPeriodDescToPomAndOrganisationTables.cs, src/EPR.Calculator.API.Data/Scripts/migrations.sql, src/EPR.Calculator.API.UnitTests/CalculatorInternalControllerTest.cs, src/EPR.Calculator.API/Controllers/CalculatorInternalController.cs
1. Added Migrations for results metadata tables in the paycal database.
2. Added defaults values to 3 master tables: 
Cost Type, 
Material,
Country,
3. Added the Migration for a New Column for POM and ORD data tables
=> Added Migrations for results metadata tables in the paycal database,

src/EPR.Calculator.API.UnitTests/CalcResultsExporterTests.cs, src/EPR.Calculator.API.UnitTests/EPR.Calculator.API.UnitTests.csproj, src/EPR.Calculator.API.UnitTests/Exporter/CalcResultsFileNameTests.cs, src/EPR.Calculator.API/Exporter/CalcResultsExporter.cs, src/EPR.Calculator.API/Exporter/CalcResultsFileName.cs
Change the format used for the calculation report's file name
=> Change the format used for the calculation result file name

src/EPR.Calculator.API.UnitTests/BaseControllerTest.cs, src/EPR.Calculator.API.UnitTests/CalcResultsExporterTests.cs, src/EPR.Calculator.API.UnitTests/CalculatorControllerTests.cs, src/EPR.Calculator.API.UnitTests/DownloadResultFileTest.cs, src/EPR.Calculator.API.UnitTests/PutCalculatorRunStatusTest.cs, src/EPR.Calculator.API/Controllers/CalculatorController.cs, src/EPR.Calculator.API/Exporter/CalcResultsExporter.cs, src/EPR.Calculator.API/Program.cs, src/EPR.Calculator.API/Services/BlobStorageService.cs, src/EPR.Calculator.API/Services/IStorageService.cs, src/EPR.Calculator.API/Services/LocalFileStorageService.cs
Changes related to BlobStorage Download File
Also, changed the way the File is written to BlobStorage
=> Download Results file changes

src/EPR.Calculator.API.UnitTests/Controllers/LapcapDataControllerTests.cs, src/EPR.Calculator.API/Builder/Summary/TotalBillBreakdown/TotalBillBreakdownHeaders.cs, src/EPR.Calculator.API/Controllers/LapcapDataController.cs
493247 Make create lapcap data endpoint async
=> Make create lapcap data endpoint async

src/EPR.Calculator.API.UnitTests/Controllers/DefaultParameterSettingControllerTests.cs, src/EPR.Calculator.API.UnitTests/Validator/DefaultParameterSettingControllerValidationTest.cs, src/EPR.Calculator.API/Controllers/DefaultParameterSettingController.cs
Created default paramater settings endpoint async
=> Make create default paramater settings endpoint async

src/EPR.Calculator.API.UnitTests/Controllers/LapcapDataControllerTests.cs, src/EPR.Calculator.API/Controllers/LapcapDataController.cs
Added async to the get endpoint of the lapcap data
=> Make get lapcap data controller endpoint async

src/EPR.Calculator.API.UnitTests/Controllers/LapcapDataControllerTests.cs, src/EPR.Calculator.API/Controllers/LapcapDataController.cs
495080 Make get lapcap data endpoint async
=> Make get lapcap data endpoint async

src/EPR.Calculator.API/Controllers/CalculatorController.cs, src/EPR.Calculator.API/HealthCheck/HealthCheckOptionsBuilder.cs, src/EPR.Calculator.API/Program.cs
Introduces a health check endpoint allowing anonymous requests. Returns 'healthy' and a 200 response code.
=> Add health check endpoint

src/EPR.Calculator.API.UnitTests/Controllers/CalculatorNewControllerTests.cs, src/EPR.Calculator.API/Constants/CommonConstants.cs, src/EPR.Calculator.API/Controllers/CalculatorNewController.cs, src/EPR.Calculator.API/appsettings.json
Removing BillingJsonFileName Example_sample_message_Producer_billing file_1.0.json
=> Removing BillingJsonFileName Example_sample_message_Producer_billing

src/EPR.Calculator.API.UnitTests/Controllers/GetCalculatorRunTest.cs, src/EPR.Calculator.API/Dtos/CalculatorRunDto.cs, src/EPR.Calculator.API/Mappers/CalcRunMapper.cs
Add is_billing_file_generating to /v1/calculatorRuns/{runId}
=> Add is_billing_file_generating to /v1/calculatorRuns/{runId}

src/EPR.Calculator.API.UnitTests/Controllers/CalculatorNewControllerTests.cs, src/EPR.Calculator.API/Controllers/CalculatorNewController.cs
=> Update the billing_file_authorised_date

src/EPR.Calculator.API.Data/DataModels/CalculatorRun.cs, src/EPR.Calculator.API.Data/Migrations/20250709123908_RemoveColumnHasBillingFileGenerated.Designer.cs, src/EPR.Calculator.API.Data/Migrations/20250709123908_RemoveColumnHasBillingFileGenerated.cs, src/EPR.Calculator.API.Data/Scripts/migrations.sql, src/EPR.Calculator.API.Data/TypeConfigurations/CalculatorRunConfiguration.cs, src/EPR.Calculator.API.UnitTests/Controllers/CalculatorNewControllerTests.cs, src/EPR.Calculator.API.UnitTests/Services/BillingFileServiceTests.cs, src/EPR.Calculator.API.UnitTests/Validator/CalculatorRunStatusDataValidatorTest.cs, src/EPR.Calculator.API.UnitTests/Validators/ProducerBillingInstructionsRequestDtoDataValidatorTests.cs, src/EPR.Calculator.API/Controllers/BillingFileController.cs, src/EPR.Calculator.API/Controllers/CalculatorController.cs, src/EPR.Calculator.API/Controllers/CalculatorNewController.cs, src/EPR.Calculator.API/Services/BillingFileService.cs, src/EPR.Calculator.API/Validators/CalculatorRunStatusDataValidator.cs
1. Remove HasBillingFileGenerated column and its udages https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/580704 -  code referring to it
2. https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/580465 - Download the latest billing file
3. https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/582679 - Modify endpoint  prepareBillingFileSendToFSS/{runId}
=> Download the latest billing file

src/EPR.Calculator.API.UnitTests/Controllers/CalculatorControllerTests.cs, src/EPR.Calculator.API/Controllers/CalculatorController.cs, src/EPR.Calculator.API/Validators/CalcFinancialYearRequestDtoDataValidator.cs, src/EPR.Calculator.API/Validators/ICalcFinancialYearRequestDtoDataValidator.cs
https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/586003
=> Logic to restrict PUT for INITIAL Run
